# Python Basics Programming Assignment

### Q1.	Write a Python program to find sum of elements in list?

In [17]:
import numpy as np
while True:
    try:
        num_ele=int(input("Enter Number of elements in list "))
        if num_ele<=0:
            print("Enter a positive number")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)
        
num_list=[]
for i in range(1,num_ele+1):
    num=int(input("Enter {} st number in list".format(i)))
    num_list.append(num)
    
print("Number list is as below:")
print(num_list)
np_list=np.array(num_list)
print(np_list)
total=np.sum(np_list)
print(total)

Enter Number of elements in list 5
Enter 1 st number in list45
Enter 2 st number in list54
Enter 3 st number in list21
Enter 4 st number in list235
Enter 5 st number in list52
Number list is as below:
[45, 54, 21, 235, 52]
[ 45  54  21 235  52]
407


### Q2.	Write a Python program to  Multiply all numbers in the list?

In [23]:
import numpy as np
while True:
    try:
        num_ele=int(input("Enter Number of elements in list "))
        if num_ele<=0:
            print("Enter a positive number")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)
        
num_list=[]
for i in range(1,num_ele+1):
    num=int(input("Enter {} st number in list".format(i)))
    num_list.append(num)
    
print("Number list is as below:")
print(num_list)
np_list=np.array(num_list)
print(np_list)
mul_num=np.prod(np_list)
print("Multiplications of numbers in list is ",mul_num)

Enter Number of elements in list 3
Enter 1 st number in list4
Enter 2 st number in list3
Enter 3 st number in list10
Number list is as below:
[4, 3, 10]
[ 4  3 10]
Multiplications of numbers in list is  120


### Q3.	Write a Python program to find smallest number in a list?

In [18]:
import numpy as np
while True:
    try:
        num_ele=int(input("Enter Number of elements in list "))
        if num_ele<=0:
            print("Enter a positive number")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)
        
num_list=[]
for i in range(1,num_ele+1):
    num=int(input("Enter {} st number in list".format(i)))
    num_list.append(num)
    
print("Number list is as below:")
print(num_list)
np_list=np.array(num_list)
print(np_list)
min_num=np.min(np_list)
print("Minimum number in list is ",min_num)

Enter Number of elements in list 5
Enter 1 st number in list78
Enter 2 st number in list41
Enter 3 st number in list21
Enter 4 st number in list296
Enter 5 st number in list71
Number list is as below:
[78, 41, 21, 296, 71]
[ 78  41  21 296  71]
Minimum number in list is  21


### Q4.	Write a Python program to find largest number in a list?

In [19]:
import numpy as np
while True:
    try:
        num_ele=int(input("Enter Number of elements in list "))
        if num_ele<=0:
            print("Enter a positive number")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)
        
num_list=[]
for i in range(1,num_ele+1):
    num=int(input("Enter {} st number in list".format(i)))
    num_list.append(num)
    
print("Number list is as below:")
print(num_list)
np_list=np.array(num_list)
print(np_list)
max_num=np.max(np_list)
print("Largest number in list is ",max_num)

Enter Number of elements in list 5
Enter 1 st number in list74
Enter 2 st number in list89
Enter 3 st number in list789
Enter 4 st number in list45
Enter 5 st number in list12
Number list is as below:
[74, 89, 789, 45, 12]
[ 74  89 789  45  12]
Largest number in list is  789


### Q5.	Write a Python program to find second largest number in a list?

In [24]:
import numpy as np
while True:
    try:
        num_ele=int(input("Enter Number of elements in list "))
        if num_ele<=0:
            print("Enter a positive number")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)
        
num_list=[]
for i in range(1,num_ele+1):
    num=int(input("Enter {} st number in list".format(i)))
    num_list.append(num)
    
print("Number list is as below:")
print(num_list)
np_list=np.array(num_list)
print(np_list)
np.sort(np_list)
print("Second largest number in list is ",np_list[-2])

Enter Number of elements in list 5
Enter 1 st number in list1
Enter 2 st number in list2
Enter 3 st number in list3
Enter 4 st number in list4
Enter 5 st number in list5
Number list is as below:
[1, 2, 3, 4, 5]
[1 2 3 4 5]
Second largest number in list is  4


### Q6.	Write a Python program to find N largest elements from a list?

In [27]:
import numpy as np
while True:
    try:
        num_ele=int(input("Enter Number of elements in list "))
        n_large=int(input("Enter N Largest element required"))
        if num_ele<=0:
            print("Please enter positive number")
            continue
        elif num_ele>num_ele:
            print("N largest element cannot be greater total number of elements in list")
        else:
            break
    except Exception as e:
        print("Error Occured",e)
        
num_list=[]
for i in range(1,num_ele+1):
    num=int(input("Enter {} st number in list".format(i)))
    num_list.append(num)
    
print("Number list is as below:")
print(num_list)
np_list=np.array(num_list)
print(np_list)
np.sort(np_list)
print("Second largest number in list is ",np_list[-n_large])

Enter Number of elements in list 5
Enter N Largest element required3
Enter 1 st number in list9
Enter 2 st number in list87
Enter 3 st number in list5
Enter 4 st number in list4
Enter 5 st number in list1
Number list is as below:
[9, 87, 5, 4, 1]
[ 9 87  5  4  1]
Second largest number in list is  5


###  Q7.	Write a Python program to print even numbers in a list?

In [28]:
import numpy as np
while True:
    try:
        num_ele=int(input("Enter Number of elements in list "))
        if num_ele<=0:
            print("Enter a positive number")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)
        
num_list=[]
for i in range(1,num_ele+1):
    num=int(input("Enter {} st number in list".format(i)))
    num_list.append(num)
    
print("Number list is as below:")
print(num_list)

print("Even numbers is list")
for ele in num_list:
    if ele%2==0:
        print(ele)

Enter Number of elements in list 5
Enter 1 st number in list4
Enter 2 st number in list56
Enter 3 st number in list41
Enter 4 st number in list23
Enter 5 st number in list71
Number list is as below:
[4, 56, 41, 23, 71]
Even numbers is list
4
56


### Q8.	Write a Python program to print odd numbers in a List?

In [30]:
import numpy as np
while True:
    try:
        num_ele=int(input("Enter Number of elements in list "))
        if num_ele<=0:
            print("Enter a positive number")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)
        
num_list=[]
for i in range(1,num_ele+1):
    num=int(input("Enter {} st number in list".format(i)))
    num_list.append(num)
    
print("Number list is as below:")
print(num_list)

print("Odd numbers is list")
for ele in num_list:
    if ele%2!=0:
        print(ele)

Enter Number of elements in list 5
Enter 1 st number in list14
Enter 2 st number in list78
Enter 3 st number in list41
Enter 4 st number in list33
Enter 5 st number in list61
Number list is as below:
[14, 78, 41, 33, 61]
Odd numbers is list
41
33
61


### Q9.	Write a Python program to Remove empty List from List?

In [34]:
list1=[5,7,8,[],5,2,[]]

print("First list ", list1)

full_list=[ele for ele in list1 if ele!=[] ]
print("List without empty list ",full_list)

First list  [5, 7, 8, [], 5, 2, []]
List without empty list  [5, 7, 8, 5, 2]


### Q10.	Write a Python program to Cloning or Copying a list?

In [31]:
import numpy as np
while True:
    try:
        num_ele=int(input("Enter Number of elements in list "))
        if num_ele<=0:
            print("Enter a positive number")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)
        
num_list=[]
for i in range(1,num_ele+1):
    num=input("Enter {} st number in list".format(i))
    num_list.append(num)
    
print("Number list is as below:")
print(num_list)

clone_list=num_list.copy()
print("Copied List is as below :")
print(clone_list)

Enter Number of elements in list 5
Enter 1 st number in list1
Enter 2 st number in list2
Enter 3 st number in list3
Enter 4 st number in list4
Enter 5 st number in list5
Number list is as below:
[1, 2, 3, 4, 5]
Copied List is as below :
[1, 2, 3, 4, 5]


### Q11.	Write a Python program to Count occurrences of an element in a list?

In [33]:
import numpy as np
while True:
    try:
        num_ele=int(input("Enter Number of elements in list "))
        occurance=input("Element to check occurance")
        if num_ele<=0:
            print("Enter a positive number")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)
        
num_list=[]
for i in range(1,num_ele+1):
    num=input("Enter {} st number in list".format(i))
    num_list.append(num)
    
print("Number list is as below:")
print(num_list)

print("Occurance of element {} in list is ".format(occurance),num_list.count(occurance))

Enter Number of elements in list 5
Element to check occurance3
Enter 1 st number in list1
Enter 2 st number in list2
Enter 3 st number in list3
Enter 4 st number in list3
Enter 5 st number in list4
Number list is as below:
['1', '2', '3', '3', '4']
Occurance of element 3 in list is  2
