# Python Basics Programming Assignment 8

### Q1.	Write a Python Program to Add Two Matrices?

In [9]:
import numpy as np
#Take number of rows and columns in matrices req
while True:
    try :
        rows=int(input("Input number of rows in matrices"))
        cols=int(input("Input number of columns in matrices"))
        if cols<1 or rows<1:
            print("Enter Number greater than or equal to one")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)

matrix1= []

for i in range(rows):     
    a =[]
    for j in range(cols):
        b=int(input("Enter element at row {0} and column {1} for matrix 1".format(i,j)))
        a.append(b)
    matrix1.append(a)

matrix2 = []

for i in range(rows):     
    a =[]
    for j in range(cols):
        b=int(input("Enter element at row {0} and column {1} for matrix 2".format(i,j)))
        a.append(b)
    matrix2.append(a)
print(matrix1)
print(matrix2)

def matrix_add(matrix1, matrix2):
    A=np.array(matrix1)
    B=np.array(matrix2)
    return A+B

print("Addition of matrices")
matrix_add(matrix1,matrix2)

Input number of rows in matrices2
Input number of columns in matrices2
Enter element at row 0 and column 0 for matrix 11
Enter element at row 0 and column 1 for matrix 12
Enter element at row 1 and column 0 for matrix 13
Enter element at row 1 and column 1 for matrix 14
Enter element at row 0 and column 0 for matrix 25
Enter element at row 0 and column 1 for matrix 26
Enter element at row 1 and column 0 for matrix 27
Enter element at row 1 and column 1 for matrix 28
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
Addition of matrices


array([[ 6,  8],
       [10, 12]])

### Q2.	Write a Python Program to Multiply Two Matrices?

In [10]:
import numpy as np
#Take number of rows and columns in matrices req
while True:
    try :
        rows=int(input("Input number of rows in matrices"))
        cols=int(input("Input number of columns in matrices"))
        if cols<1 or rows<1:
            print("Enter Number greater than or equal to one")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)

matrix1= []

for i in range(rows):     
    a =[]
    for j in range(cols):
        b=int(input("Enter element at row {0} and column {1} for matrix 1".format(i,j)))
        a.append(b)
    matrix1.append(a)

matrix2 = []

for i in range(rows):     
    a =[]
    for j in range(cols):
        b=int(input("Enter element at row {0} and column {1} for matrix 2".format(i,j)))
        a.append(b)
    matrix2.append(a)
print(matrix1)
print(matrix2)

def matrix_mul(matrix1, matrix2):
    A=np.array(matrix1)
    B=np.array(matrix2)
    return A.dot(B)

print("Addition of matrices")
matrix_mul(matrix1,matrix2)

Input number of rows in matrices2
Input number of columns in matrices2
Enter element at row 0 and column 0 for matrix 11
Enter element at row 0 and column 1 for matrix 12
Enter element at row 1 and column 0 for matrix 13
Enter element at row 1 and column 1 for matrix 14
Enter element at row 0 and column 0 for matrix 25
Enter element at row 0 and column 1 for matrix 26
Enter element at row 1 and column 0 for matrix 27
Enter element at row 1 and column 1 for matrix 28
[[1, 2], [3, 4]]
[[5, 6], [7, 8]]
Addition of matrices


array([[19, 22],
       [43, 50]])

### Q3.	Write a Python Program to Transpose a Matrix?

In [11]:
import numpy as np
#Take number of rows and columns in matrices req
while True:
    try :
        rows=int(input("Input number of rows in matrices"))
        cols=int(input("Input number of columns in matrices"))
        if cols<1 or rows<1:
            print("Enter Number greater than or equal to one")
            continue
        else:
            break
    except Exception as e:
        print("Error Occured",e)

matrix1= []

for i in range(rows):     
    a =[]
    for j in range(cols):
        b=int(input("Enter element at row {0} and column {1} for matrix 1".format(i,j)))
        a.append(b)
    matrix1.append(a)

print(matrix1)

def matrix_trans(matrix1):
    A=np.array(matrix1)
    return A.transpose()

print("Addition of matrices")
matrix_trans(matrix1)

Input number of rows in matrices2
Input number of columns in matrices2
Enter element at row 0 and column 0 for matrix 11
Enter element at row 0 and column 1 for matrix 12
Enter element at row 1 and column 0 for matrix 13
Enter element at row 1 and column 1 for matrix 14
[[1, 2], [3, 4]]
Addition of matrices


array([[1, 3],
       [2, 4]])

### Q4.	Write a Python Program to Sort Words in Alphabetic Order?

In [36]:
import re
#Taking user input to enter number of words
while True:
    try:
        words_num=int(input("Enter the total number of words"))
        if words_num<=1:
            print("Atleast two words must be inputed for sorting")
            continue 
        else:
            break
    except Exception as e:
        print("Error occured",e)
        continue
        
word_list=[]
#Take input of words
try:
    for i in range(words_num):
        word=input("Enter word {} ".format(i+1))
        word_list.append(word.lower())  
        
except Exception as e:
    print("Error occured", e)
print(word_list)

def aplha_order(word_list):
    word_list.sort()
    for word in word_list:
        print(word)

print("Words in alphabetic orders")
aplha_order(word_list)

Enter the total number of words5
Enter word 1 In
Enter word 2 an
Enter word 3 alphabetical
Enter word 4 order
Enter word 5 please
['in', 'an', 'alphabetical', 'order', 'please']
Words in alphabetic orders
alphabetical
an
in
order
please


### Q5.	Write a Python Program to Remove Punctuation From a String? 

In [40]:
string=input("Enter a String")
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
no_punct = ""
for char in string:
    if char not in punctuations:
        no_punct = no_punct + char
        
print("String without punctuations ")
print(no_punct)

Enter a StringLook!! Out There.
String without punctuations 
Look Out There
